// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8qlmEHVdZ5Qm7kq5wpXYCUf70br-DexY',
    appId: '1:880681485138:web:3c86071105bd086fdd308b',
    messagingSenderId: '880681485138',
    projectId: 'neuroguard-cab3d',
    authDomain: 'neuroguard-cab3d.firebaseapp.com',
    databaseURL: 'https://neuroguard-cab3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'neuroguard-cab3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAChw8QAL60zzchymx_4B0IfjXvj12Hq4o',
    appId: '1:10529329568:android:1fc10082530019f480d4c5',
    messagingSenderId: '10529329568',
    projectId: 'neuroguard-1f865',
    storageBucket: 'neuroguard-1f865.firebasestorage.app',
  );

}