// lib/core/models/alert_model.dart
//
// CHANGES FROM ORIGINAL:
//   • Added optional `escalationId` field — a UUID shared by all tiers of one
//     alert chain. Lets EscalationService find and escalate the original entry.
//   • toMap() emits escalationId into metadata automatically when present.

import 'package:cloud_firestore/cloud_firestore.dart';

enum AlertType { geoFence, medicine, spyCall, matSensor }
enum AlertSeverity { info, warning, critical }

class AlertModel {
  final AlertType type;
  final String message;
  final AlertSeverity severity;
  final Map<String, dynamic> metadata;

  /// Shared across all tiers of one escalation chain.
  /// Generated by the caller (e.g., AlertService.send) and passed into
  /// EscalationService.begin() so Tier 3 can locate and upgrade this entry.
  final String? escalationId;

  const AlertModel({
    required this.type,
    required this.message,
    this.severity    = AlertSeverity.warning,
    this.metadata    = const {},
    this.escalationId,
  });

  Map<String, dynamic> toMap() {
    final meta = Map<String, dynamic>.from(metadata);
    if (escalationId != null) meta['escalationId'] = escalationId;

    return {
      'type':      type.name,
      'message':   message,
      'severity':  severity.name,
      'timestamp': FieldValue.serverTimestamp(),
      'isRead':    false,
      'metadata':  meta,
    };
  }
}